[context.develop.environment]
  YARN_VERSION = "1.22.10"
  NODE_VERSION = "14"

[context.master.environment]
  YARN_VERSION = "1.22.10"
  NODE_VERSION = "14"

[build]
  command = "yarn run build"
  functions = "out_functions"
  publish = "out_publish"

[[plugins]]
  package = "@netlify/plugin-nextjs"